Chords above text
LipAnn/SongsChordsBot pull request #41
Opened 2023-12-20 12:23 UTC by sanchepuk

Placed Chords above Text, ended formatter

2023-12-20 12:23 UTC, pep8speaks commented
Hello @sanchepuk! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`backend/formatter.py`](https://github.com/LipAnn/SongsChordsBot/blob/9d222d9a748e3886343e86d86aebaa6758b74faa/backend/formatter.py):

> [Line 54:80](https://github.com/LipAnn/SongsChordsBot/blob/9d222d9a748e3886343e86d86aebaa6758b74faa/backend/formatter.py#L54): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 64:21](https://github.com/LipAnn/SongsChordsBot/blob/9d222d9a748e3886343e86d86aebaa6758b74faa/backend/formatter.py#L64): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 64:80](https://github.com/LipAnn/SongsChordsBot/blob/9d222d9a748e3886343e86d86aebaa6758b74faa/backend/formatter.py#L64): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 69:21](https://github.com/LipAnn/SongsChordsBot/blob/9d222d9a748e3886343e86d86aebaa6758b74faa/backend/formatter.py#L69): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 69:80](https://github.com/LipAnn/SongsChordsBot/blob/9d222d9a748e3886343e86d86aebaa6758b74faa/backend/formatter.py#L69): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 79 characters)

2023-12-20 20:08 UTC, LipAnn requested changes

2023-12-20 20:08 UTC, LipAnn commented on backend/formatter.py
> +        full_time = 0
Давай хотя бы немного опишем в докстринге словами, как она совмещает аккорды с текстом
Досктринг пишется в многострочном комментарии
"""
Docstring
"""

2023-12-21 06:47 UTC, LipAnn approved these changes

2023-12-21 06:48 UTC, Herbstblatt requested changes

2023-12-21 06:53 UTC, Herbstblatt approved these changes

2023-12-21 06:53 UTC, merged